### ISSUE TITLE
Duplicate Marital Status on Multiple Tabs

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#1]
**DD Issue**
There are two sets of marital status entries in the DD spreadsheet (See DD rows 1251 and 1741 https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us/edit#gid=1138104744&fvid=184650586)  Marital status came from two different tabs.  

**Recommended action** - delete duplicate rows from the comprehensive dd and note that the element and the options came from two tabs.  

Reason for recommendation:  It is most helpful to have a data dictionary without duplicates regardless of what tabs the data came from.  

**Next step:**  Looking for agreement from WHO that the comprehensive data dictionary should not contain duplicate entries.

**Comment by natschja** [comment]
Yes, the final data dictionary should only have a single data element once (per health domain of course), and that data element should be linked to the first point of data collection. So for martial status, it would be during registration.

**Comment by natschja** [comment]
Just to note, Jenny is still working on finalizing everything so there will be a 'cleaner' data dictionary by the end of the year.
