### ISSUE TITLE
Follow up contact recommended date - not clear what this is

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#100]
@natschja we are not sure what this is.  Is it a date to follow up with the patient to ensure they are better?  Is it outreach to see why the patient did not show up.  What is the context here?

**Comment by jamlung-ri** [comment]
@jennifershivers Is this a Medical Question for WHO? I don't think this was put onto the tickets list that we sent WHO.

**Comment by jennifershivers** [comment]
We need to figure out if it is FP or STI and add it to the list.  https://docs.google.com/document/d/13I0PjzmGVj8kEYca1HJa-_dBGFegFp610jcMcxXj9C4/edit

**Comment by jamlung-ri** [comment]
This is from the FP side, so I added it to the FP list.

**Comment by jamlung-ri** [comment]
We mapped this to the scheduled[x] resource in a CarePlan (Follow-up) profile.
