### ISSUE TITLE
Stage of syphilis - there are more than this in the terminology

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#102]

**Comment by jennifershivers** [comment]
2169 | Stage of Syphilis condition | 2169 | Stage of condition | Stage of condition | Data Element
-- | -- | -- | -- | -- | --
2170 | early | 2170 | early | early | Input Option
2171 | late | 2171 | late | late | Input Option
2172 | unknown | 2172 | unknown | unknown | Input Option

There are more stages than this in the terminology.  Do you want more than this, or is this all that is needed to support the desired decision making?

**Comment by jamlung-ri** [comment]
We elected not to add any more conditions to this term.
