### ISSUE TITLE
Core IG Number of births and number of pregnancies

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#105]
Looks like number of births is coding to a code where it should have a code indicating the question (number of births) and a place for the numerical answer.  

Number of pregnancies should work the same.

**Comment by jennifershivers** [comment]
May be related - 

1283 | Date of last sexual intercourse
is coding to a code and not the date

**Comment by terrycullen** [comment]
feel free to change.i thought that intercourse-- coding to intercourse and then ADD the date; there isnt any other way to get this; there isnt a code for a date

**Comment by jennifershivers** [comment]
@terrycullen This ticket is for the implementation guide, not the terminology coding.  I think it may be resolved.
