### ISSUE TITLE
Mapping 2179 - STI Treatment recommendation

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#107]
For ID 2179 - "STI Treatment recommendation" and its input options, we need to figure out which FHIR resource is best so that appropriate terminology codes can be attributed.

The following resources in the [CarePlan resource](https://www.hl7.org/fhir/careplan.html) are available:

- [reasonCode](https://www.hl7.org/fhir/careplan-definitions.html#CarePlan.activity.detail.reasonCode) - Why activity should be done
   - With this resource, we want terminology codes for the condition to be treated

- [product[x]](https://www.hl7.org/fhir/careplan-definitions.html#CarePlan.activity.detail.product_x_) - Identifies the food, drug or other product to be consumed or supplied in the activity
   - With this resource, we want terminology codes for the drug to be used as treatment

Which resource should we pick? @sliver007 is there a way for us to include both in the structure definition?

**Comment by terrycullen** [comment]
should we do a value set? OR, Is this more the recommendations. per se? which I think would be a medication given that it is a treatment (and treatment for STI is. usually medications)

**Comment by jamlung-ri** [comment]
We put this in the reasonCode resource, since the input options were diseases. This will allow the users to select the drug they use to treat the illness.
