### ISSUE TITLE
 "Any other detail of clinical significance" #1801

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#11]
Is this patient's transfer notes?  Need a little more context to map to FHIR

**Comment by jamlung-ri** [comment]
@jennifershivers Is this something that Terry should be answering? Or should this be for Nat instead?

**Comment by jennifershivers** [comment]
I think this might just be a text field in that applicaable resource. But we need a bit more context.

**Comment by jamlung-ri** [comment]
Resolved with FHIR mapping
