### ISSUE TITLE
Question:  Modeling Concept and Answer?  

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#12]
Question:  Modeling Concept and Answer?  
Many of the questions (‘ever had sex’) can be answered as a yes/no OR they can be answered with a clinical concept (virgin).  LOINC terminology can answer the question and provide an example for an answer; SNOMED can provide a code for the clinical concept. We assume that both question answer as well as clinical concept should be included in the terminology specifications. 

In addition. SNOMED rarely codes questionnaires; the vast majority of questionnaire coding is done using LOINC, and many questionnaires have not been coded.

**Comment by jamlung-ri** [comment]
We have been able to resolve this issue over multiple conversations in the past two months.
