### ISSUE TITLE
Unspecified Input Options for Multiple Choice

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#14]
In several rows of the data dictionary, the data type is Multiple Choice, but there are no input options listed below. How should we proceed with this? Some possible suggestions:

1. RI team populates with answers present in a standard value set like FHIR.
1. We post the question here and allow someone at WHO to list out input options.
1. We leave the data dictionary as is, without specifying any input options.

**Comment by jennifershivers** [comment]
I think the contraception method options are 1287 - 1314.  Is that correct?  @natschja

**Comment by jamlung-ri** [comment]
Another good example is row 1799, which is level of urgency. It is multiple choice, but I don't see any input options for it.

**Comment by natschja** [comment]
This should be addressed by the updated data dictionary. However, finalizing the list of contraception methods was a tricky  - linked (https://docs.google.com/spreadsheets/d/1JhPlRchpy47jpFTVCL7bsro813Vlx-bio-YpXdSfpg8/edit?ts=5dfb28b6#gid=1143146581) is the **finalized** list of contraception methods from our WHO colleague leading the FP work. Also pasted below for quick referencing - as the above spreadsheet is also shared with Ona who's creating an OpenSRP based FP reference module. 

**Intrauterine devices**
Copper-bearing intrauterine devices (Cu-IUDs)
Levonorgestrel IUD (LNG-IUD)
**Implants**
Etonogestrel (ETG) one-rod
Levonorgestrel (LNG) two-rod
**Injectables**
DMPA-IM  DMPA, administered intramuscularly
DMPA-SC  DMPA, administered subcutaneously
NET-EN norethisterone enanthate
Progestogen-only pills (POP)
Combined oral contraceptives (COCs)
Combined contraceptive patch 
Combined contraceptive vaginal ring (CVR)
Progesterone-releasing vaginal ring (PVR)
Lactational amenorrhea method (LAM)
**Barrier method**
Male Condoms
Female Condoms
Emergency contraceptive pills (ECPs)
Fertility awareness-based methods (FAB)
Male sterilization
Female sterilization
Withdrawal

**Comment by jennifershivers** [comment]
Closing this one - remaining issues seems to be STI medications
