### ISSUE TITLE
education level 

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#15]
1746 "Highest level of education achieved"  

Issue:  Not FHIR answer to map to "no education"  

Options - propose FHIR add an option for none?  

@brynrhodes @jamlung-ri

**Comment by jamlung-ri** [comment]
We are using the AY column to mark "No FHIR valueset code available". This will mark the input options that need to be added to a value set. @sliver007 @brynrhodes @jbyrdevans @jreyno77 @SeanWheelwright
