### ISSUE TITLE
Data modeling injection date etc.  

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#16]
Elements 1315 - 1318 seem to belong with a procedure.  Need to determine how to model these.

**Comment by jamlung-ri** [comment]
For context, these rows are all related to row 1286 ("Birth control method reported at intake") and its input options 1287-1314, which consist of various birth control methods. If the end user selects an IUD as the birth control method, then row 1317 ("IUD Insertion Date") would be associated with that.

**Comment by jennifershivers** [comment]
Proposal - 
For each question about types of contraception, split into multiple separate questions (Devices / medications / procedures etc).  Each of them will have an option for "none".   Need to determine if these lists are limited to the options in the DD (Do you want all devices in FHIR included or just the contraception ones)  - verify with @natschja  - Suggest using an extensible value set in a profile.

**Comment by jamlung-ri** [comment]
We have resolves this. See [Ticket 29](https://github.com/who-int/Data-Dictionary-Mapping/issues/29).
