### ISSUE TITLE
Information source for pregnancy status - Urine and Blood tests

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#17]
@terrycullen asks: is this the test OR a positive result?

Nat, can you provide some clarification or link us to your clinical people that may be able to help us?

Reference: [Rows 1276-1277](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by natschja** [comment]
The process for using pregnancy tests is in the process of being clarified as pregnancy tests would only be used during a FP encounter if the woman is reasonably pregnant (as per the guideline in the handbook) - so i think these data elements are being updated accordingly. 

To answer @terrycullen 's question, these input options would be noting the tests conducted whereas the earlier data element of pregnant/not pregnant would indicate the result.

**Comment by jennifershivers** [comment]
I no longer find this in the DD   - closing
