### ISSUE TITLE
Sensitivity of pregnancy test

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#18]
@terrycullen asks: 

not sure what this is trying to ascertain; would be different for maker and user of testNat, can you provide some clarification or link us to your clinical people that may be able to help us?

All pregnancy tests look at HCG levels and are highly sensitive. Needs clarification.

Reference: [Rows 1280-1281](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by natschja** [comment]
If I recall correctly, I think this data element might be removed...I'll have to get back to you on this after seeing the updated version as this was also a question Ona brought up as they're building the OpenSRP module.

**Comment by jamlung-ri** [comment]
@natschja The updated data dictionary still has these terms in there. Do you have any further guidance for us?

**Comment by jennifershivers** [comment]
Here are some options for coding 
LOINC	Name	R/O/C	Cardinality	Example UCUM Units
86644-2	Pregnancy lab tests - FPAR 2.0 set			
2106-3	Choriogonadotropin (pregnancy test) [Presence] in Urine			
2118-8	Choriogonadotropin (pregnancy test) [Presence] in Serum or Plasma			
19080-1	Choriogonadotropin [Units/volume] in Serum or Plasma			m[IU]/mL
21198-7	Choriogonadotropin.beta subunit [Units/volume] in Serum or Plasma			[IU]/mL
2110-5	Choriogonadotropin.beta subunit (pregnancy test) [Presence] in Serum or Plasma			
80385-8	Choriogonadotropin (pregnancy test) [Presence] in Serum by Rapid immunoassay

**Comment by natschja** [comment]
Hi all,

I talked to our family planning expert about this and it was determined that this data element would only be relevant at the procurement level - not necessarily the facility level. It would be a point of configuration at the population level as it has implications for scheduling follow up. (reference on page 440: https://apps.who.int/iris/bitstream/handle/10665/260156/9780999203705-eng.pdf?sequence=1). I think this warrants a larger conversation on how to deal with more higher level concepts that don't necessarily affect the care plan of one woman but of all women that are provided care in that country.

Tagging @brynrhodes  here as well.

**Comment by natschja** [comment]
Added to list of questions

**Comment by jennifershivers** [comment]
This was removed from the newer version of the FP DD.
