### ISSUE TITLE
Recent miscarriage or post-abortion - What does recent mean?

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#21]
@terrycullen asks:

For [ID 1338](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Recent miscarriage or post-abortion"), what does recent mean?

**Comment by natschja** [comment]
There's no set definition of 'recent' unfortunately. In the Provider Handbook (https://apps.who.int/iris/bitstream/handle/10665/260156/9780999203705-eng.pdf?sequence=1) recency is used loosely from 7 days, 2 weeks, and 4 weeks. The clinical practice guidelines are also the same (https://apps.who.int/iris/bitstream/handle/10665/252267/9789241565400-eng.pdf). Based on the guidelines I would say anything up to 4 weeks is "recent".

**Comment by jennifershivers** [comment]
We left abortion and miscarriage together and put both codes.
