### ISSUE TITLE
Immediate post-septic abortion

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#22]
@terrycullen asks:

For [ID 1342](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Immediate post-septic abortion"), SNOMED 41587001 is wrong ; i THINK that they want miscarriage with sepsis; we should confirm-- 67465009?

**Comment by natschja** [comment]
What is 41587001 in SNOMED?

**Comment by jamlung-ri** [comment]
41587001: Third trimester pregnancy (finding)
67465009: Miscarriage with sepsis (disorder)

Wording in Data Dictionary: Immediate post-septic abortion (an input option for "Miscarriage or abortion stage of pregnancy")

**Comment by jennifershivers** [comment]
Looking again.

**Comment by jennifershivers** [comment]
"Septic abortion refers to an abortion (either spontaneous or induced) that is then complicated by infection."  new description in the new version of the DD.

**Comment by jennifershivers** [comment]
Need to update our version of the DD with the new description.

**Comment by jamlung-ri** [comment]
I updated the DD with this new definition.
