### ISSUE TITLE
Missed or late menses - Might be ammenorhea

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#23]
@terrycullen asks:

For [ID 1344](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Missed or late menses"):
 
i think that this can be ammenorhea ; need to confirm?

**Comment by natschja** [comment]
This question is more to gauge whether there's a risk for pregnancy. Based on the ICD-11 codes (https://icd.who.int/ct11/icd11_mms/en/release), there are multiple reasons for amenorrhea that could be coded, including "unspecified" amenorrhea. So I'm not 100% sure what would be the best coding here - I would defer to your clinical expertise @terrycullen on this one...

**Comment by jennifershivers** [comment]
Looking for additional coding options.

**Comment by jamlung-ri** [comment]
We are treating Missed/Late Menses and Ammenorhea as synonyms.

**Comment by jennifershivers** [comment]
Mapped to SNOMED 161780009; 42131003; 84292000; 36521000 and LOINC LA 22280-4
