### ISSUE TITLE
Gender-based violence risk factors

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#24]
@terrycullen asks:

For [ID 1357](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Gender-based violence risk factors"), can this be a positive screen on a DV screening tool?

**Comment by natschja** [comment]
This one Tigest and I are working on hashing out a bit more as it will have to be integrated to the ANC kit as well. There's a certain level of sensitivity around this topic as Gender based violence, violence against women, screening is only recommended in the instance whereby that clinical setting/health system is equipped to manage this. There's a lot of other guidance documents we'll have to include that have detailed out the specific data elements. Those documents include Health care for women subjected to intimate partner violence or sexual violence: a clinical handbook (https://apps.who.int/iris/bitstream/handle/10665/136101/WHO_RHR_14.26_eng.pdf?sequence=1)
and Strengthening health systems to respond to women subjected to intimate partner violence or sexual violence: A manual for health managers (https://apps.who.int/iris/bitstream/handle/10665/259489/9789241513005-eng.pdf?sequence=1)

So ideally, if the setting is equipped to handle gender based violence then there would be a decision logic for screening and the data captured would lead to an output of Y/N this woman is at risk.

**Comment by jamlung-ri** [comment]
We have decided not to use LOINC's screening tools, and without having input options associated with the question, we probably cannot do much FHIR mapping with it. Please advise @natschja.

**Comment by jamlung-ri** [comment]
We mapped this to a general Observation resource, but it still does not have a terminology code that we could find. It was placed in the WHO Extended Content code system.
