### ISSUE TITLE
Sexually active - Timeframe?

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#25]
@terrycullen asks:

For [ID 1358](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Sexually active"), what is the timeframe for being sexually active?

**Comment by natschja** [comment]
Don't think there's a time frame - it's just if the person has ever had sex (self-reported)

**Comment by jennifershivers** [comment]
We have coded this to  non-virgin
