### ISSUE TITLE
Risk assessment conducted - What risk?

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#26]
@terrycullen asks:

For [ID 1359](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Risk assessment conducted"): 

What is the risk assessment for? STI? pregnancy??

**Comment by natschja** [comment]
This was intended as a risk assessment to determine if the individual is part of a high risk population (e.g. sex workers), so in this context it would be at a high risk of STIs.

**Comment by jamlung-ri** [comment]
Terry was able to identify a relevant ICD10 code. Thanks Nat!
