### ISSUE TITLE
Gender-based violence victim

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#27]
@terrycullen asks:

For [ID 1356](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Gender-based violence victim"): 

does this want a code for domestic violence? there isnt a code for DV victim as far as I know

**Comment by natschja** [comment]
Added to list of questions

**Comment by jamlung-ri** [comment]
This was coded to SNOMED's Domestic Violence code.
