### ISSUE TITLE
Assigning terminology code to "Other"

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#28]
@terrycullen asks:

For [ID 1324](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) ("Other", an input option to "Reason for no contraceptive method - Reported at intake"): 

if there isn't a list to choose from, there cant be a code (at least, I cant figure out how there can be one)

**Comment by natschja** [comment]
I think this might be a question for @brynrhodes - how would you handle ambiguity in coding here? I think there are a number of input options that are "other" to accommodate for data capture that might not be reflected in the preset list.

**Comment by brynrhodes** [comment]
I'm not sure there's a single best-practice here, but I would suggest defining an "Other" code in the Core IG (CodeSystem http://www.who.int/fhir/CodeSystem/core-codes) and use that as the code option for indicating Other. That code can then be reused across all the elements that have "other" as a possible input option.

**Comment by jamlung-ri** [comment]
As suggested by Bryn, we will use the Core codesystem and the code "Other" for these situations. Rows 1901-1902 display an example of how this can be used.
