### ISSUE TITLE
Proposed Extension: Contraception

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#29]
There are multiple uniquely modeled concepts related to contraception, and I don't believe they fit well into one existing FHIR resource. We should discuss this.

**Comment by jennifershivers** [comment]
Do you mean contraception method or just the general terms?

**Comment by jamlung-ri** [comment]
I am thinking that all terms where ("Medical Domain" field = Contraception) should be considered for this extension.

**Comment by jennifershivers** [comment]
Yes, I was / am looking through options this morning.  Started to look at how other implementation guides have handled this specialty information.  We also need to look at how others are using questionnaire and how others are handling medical history.

**Comment by jennifershivers** [comment]
Research notes:  
 - created for family planning http://build.fhir.org/ig/hspc/ACOG-OPA-IG/output/
- There was an early attempt at having a pregnancy resource https://www.hl7.org/FHIR/2015Dec/nehta/pregnancy-definitions.html

- Risk assessment resource is interesting "Risk assessments are a specialized type of observation. We use a specialized resource to provide a simpler mechanism to capture of a series of risks and to associate those risks with time-ranges, probabilities, etc. All risk assertions are captured at one time based on a single set of source inputs. Capture of a single risk MAY be done using the Observation class, particularly in circumstances where it's treated as a generic observation, but for consistency, all risk assessments and prognosis SHOULD be captured using RiskAssessment."

- There is a nutrition order resource - seems like a specialty care resource.  Not very mature.  

- IPS used FHIR's Observation Resource as a base for pregnancy. Might be something we can replicate. https://build.fhir.org/ig/HL7/fhir-ips/profiles.html

**Comment by jennifershivers** [comment]
1418 - 1427 seem like they should be questions under issues and concerns.

**Comment by jennifershivers** [comment]
Proposals
1.  Create multiple Observation profiles that are similar to this smoking status profile https://hl7.org/fhir/us/core/2017Jan/ValueSet-us-core-observation-ccdasmokingstatus.html - 
Profiles would be: 

- WHO-NeverUsedContraception (boolean)
- WHO-IntakeContraceptionMethod  (Contraception list) 
 - WHO-ReasonNoIntakeContraceptionMethod (Input options)
- WHO-ContraceptionMethodInMind (Contraception list) 
- WHO-CorrectContraceptionUse (Boolean)

2.  These two concepts allow for multiple answers so we need to have something where there can be multiple codes OR make them separate observations for each if an observation cannot have multiple answers.  
- WHO-PriorContraceptionMethods
- WHO-ContraceptionIssuesConcerns - for this one look at the US core condition, health-concern example

3.  These are procedures 1694- 1698 - No extension for these.  

Insertion of IUD
Insertion of subcutaneous contraceptive (procedure)
IUD removal
IUD Insertion not possible
Implant removal

4.  Procedures for 1315 - 1318

@jamlung-ri

**Comment by natschja** [comment]
Still checking if this is reflected in the updated version of the data dictionary, but I wanted to highlight it here as we're discussing the contraception methods and concepts. Looking across the multiple guidelines and resources, the list of possible FP methods are not necessarily clearly aligned. However, we've discussed with our FP expert to come up with a 'final' list of FP methods to be included and they're below. **Bolded** are the categories of contraception methods.

**Intrauterine devices**
Copper-bearing intrauterine devices (Cu-IUDs)
Levonorgestrel IUD (LNG-IUD)

**Implants**
Etonogestrel (ETG) one-rod
Levonorgestrel (LNG) two-rod

**Injectables**
DMPA-IM 
DMPA, administered intramuscularly
DMPA-SC 
DMPA, administered subcutaneously
NET-EN norethisterone enanthate

Progestogen-only pills (POP)

Combined oral contraceptives (COCs)
Combined contraceptive patch
Combined contraceptive vaginal ring (CVR)

Progesterone-releasing vaginal ring (PVR)

Lactational amenorrhea method (LAM)

**Barrier method**
Male Condoms
Female Condoms

Emergency contraceptive pills (ECPs)
Fertility awareness-based methods (FAB)
Male sterilization
Female sterilization
Withdrawal

**Comment by jamlung-ri** [comment]
Based on a conversation with DCG yesterday and with RI today, we have decided that the best way to solve this issue is to make some structural changes to the data dictionary. Rather than the question being "Birth control method reported at intake" as it is with ID 1286, it would be better to group the terms into more specific questions/data elements e.g. "Birth control _Device_ method reported at intake" or "Birth Control _Procedures_ reported at intake". 

For each question in the data dictionary where the input options are contraceptive methods (including IDs 1286, 1328, 1687, and 1958), we will split the term into multiple rows, with a row for each group. Input options will be placed appropriately within their grouped data element (i.e. "Copper-bearing intrauterine devices (Cu-IUDs)" would be an input option only for "Birth control Device method reported at intake"). 

This list represents the groupings that will be used for this change. The bold headers represent the domain and the FHIR resource to which each bulleted term will be mapped.

**Device**

- Copper-bearing intrauterine devices (Cu-IUDs)
- Levonorgestrel IUD (LNG-IUD)
- Unspecified IUD
- Implant
- Etonogestrel (ETG) one-rod implant
- Levonorgestrel (LNG) two-rod implant
- Combined contraceptive patch
- Combined contraceptive vaginal ring (CVR)
- Progesterone-releasing vaginal ring (PVR)
- Barrier method
- Male condom
- Female condom

**Medication**
- DMPA-IM DMPA, administered intramuscularly
- DMPA-SC DMPA, administered subcutaneously
- Norethisterone enanthate (NET-EN) injectable
- Emergency contraceptive pills (ECPs)
- Progestogen-only pills (POP)
- Combined oral contraceptives (COCs)
- Combined injectable contraception

**Procedure**
- Female sterilization
- Male sterilization

**CarePlan**
- Withdrawal
- Fertility awareness-based methods (FAB)
- Lactational amenorrhea method (LAM)
- Male relying on female method

Each group will also have a "No method" option pertaining to that group.

**Comment by jennifershivers** [comment]
Question do we need to create a profile?
