### ISSUE TITLE
Right data in the FHIR resource columns?  

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#3]
@brynrhodes 
Hi.  We would like see if we are mapping to FHIR like you expect.  

See columns AI, AJ and AK for rows 1247 - 1256 as examples.  
https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us/edit#gid=1138104744&fvid=184650586

**Comment by jamlung-ri** [comment]
@brynrhodes I created a filter view for you in the Spreadsheet, called Bryn's View. You can access it in the Data -> Filter Views menu. It has all the rows that Jennifer and I have attempted FHIR mapping. Can you identify any rows in this view that have the correct FHIR content in columns AI, AJ, and AK so we can use them as examples?
