### ISSUE TITLE
Need Input Options for STI Medications

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#31]
It appears like there are no options for STI Medications.  We need to get a list for these or figure out what the list is.  

Reference: [ID 1934](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by natschja** [comment]
In the updated version of the data dictionary, on the ST.3. Service Provision tab, there's a list of "Prescribed drugs" - which I think is what should go in the list of STI medication. I'll highlight this as something to confirm with Jenny though!
