### ISSUE TITLE
Core/FP/STI Decision Designation

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#33]
**Proposal for categorizing the DDs** 

Generic  Data Elements like the following can be used across clinical specialties (FP, HIV, STI and others ) are in the **WHO-Core_IG** 
Examples:  
 - demographic 
- facility information 
- referral information 
- vital signs 

**Family planning** - Items that are specific to FP or have unique family planning input options are in the FP Implementation Guide
 - reason for a FP Visit (with the reason for visit value list for FP) 
- reason for stopping contraception method
- pregnancy intention 

Things that can be important outside of family planning are in **core
- pregnancy status** 

Questions 
1367 - 1357 - gender based violence  - does it go in core or just FP
1359 - STI Risk assessment

**Comment by jamlung-ri** [comment]
See [Ticket 81](https://github.com/who-int/Data-Dictionary-Mapping/issues/81) for further discussion
