### ISSUE TITLE
how should we model medical eligibility section?

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#36]
The medical eligibility section looks like a questionnaire.  We need more background before we can model these.  Some look like medical history and some look like risk factors.  We are unclear how to handle these.

**Comment by jennifershivers** [comment]
@natschja can you help us with some background on this section?

**Comment by jamlung-ri** [comment]
Medical Eligibility was modeled by including all Observations in a "Observations affecting Medical Eligibility" profile, all Conditions in a "Conditions affecting Medical Eligibility" profile, etc.
