### ISSUE TITLE
ID 1552: Endometrial cancer

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#38]
@terrycullen asks:

This may need to include cancer of myometrium/all uterus. 

Can we verify this with a clinical SME?

Reference: [ID 1552](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by natschja** [comment]
Also from MEC https://apps.who.int/iris/bitstream/handle/10665/181468/9789241549158_eng.pdf 

Added to list of questions for experts

**Comment by jamlung-ri** [comment]
This was coded only to ICD's Endometrium.
