### ISSUE TITLE
(Presumably) Misplaced Notes and Guidelines Resources

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#4]
For IDs 1627 - 1655 of the [Master Data Dictionary](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us/edit?usp=sharing), it appears that some of the cells are in the wrong spot and need to be shifted to the left. 

![Example from ID 1627](https://user-images.githubusercontent.com/55999682/70179740-99dffa00-16ac-11ea-8423-32f3ade9ddff.png)

In this example, MEC is in the FHIR Resource column, but MEC is not a FHIR resource. The content for these two cells might need to be shifted to the left by one cell.

**Comment by natschja** [comment]
Yes that's right - MEC is referring to the medical eligibility criteria for contraceptives guideline https://www.who.int/reproductivehealth/publications/family_planning/MEC-5/en/ I think having it under the FHIR column is just a mistake
