### ISSUE TITLE
2108: Specimen collection

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#45]
@terrycullen asks:

can they give us options for Specimen collection? 

Can we verify this with a clinical SME?

Reference: [ID 2108](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by jennifershivers** [comment]
We coded this to Specimen.collection.  If more details are provided on the specimen from a specific test, we can code terminology.  If not, it will just relate to FHIR.
