### ISSUE TITLE
Handling test results in the DD

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#46]
Original title - Adding result codes for 2113: GC Screen Result #46

@terrycullen asks:

need LOINC code for test and then code for result; can we confirm this is how to approach this?

Reference: [ID 2113](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by jennifershivers** [comment]
Proposal - 2109 - 2117 

These appear to be several test "results"  
Proposed FHIR modeling structure is to model these more like the following example for CT Screen
 EX:  CT Screen - specific test with a specific test code (Observation.code) 
Last CT Screen Date (Observation.effective[x]) 
Last CT Screen Result   (Observation.component.value[x])

can you agree to this?  If so, we would remove #2109 "Test Results" as this is probably a header on a screen.  
If we agree to this, then we need to figure out how to put it in the DD.

**Comment by terrycullen** [comment]
​I agree; that is what I was trying to suggest
date, test itself (which needs to be the macro code if we can find it; in this case, CT is chlamydia which has about 30 tests) and then result (but result is difficult, right? either you have chlamydia or you dont; either y/n or +/- or present or not present. this has historically been the problem with lab values in EMRs.. not sure what to do with that hairy problem....

**Comment by terrycullen** [comment]
you NEED result to trigger the CDS ( triggered at different stages..

do you need to be screened
how do I screen you
what test do I use
what is the result
what do I do with the result... each stage could have CDS invoked

**Comment by terrycullen** [comment]
will be interesting to see what FHIR is going to do with this to trigger CDS, as it is a logic tree. and not just one OBS--unless the CDS is ONLY triggered from the result.. (but, that cant be true, since treatment in pregnancy is different than treatment in non pregnancy).

**Comment by jamlung-ri** [comment]
I agree that ID 2109 can be removed since it provides no meaningful content.

When mapping test result to FHIR, we should keep the mapping general and not specify a value type (e.g. integer, code, boolean, etc.). This would allow the healthcare facilities using our implementation guide to specify which tests they are using, rather than mandating that they use certain tests.

**Comment by jennifershivers** [comment]
@natschja Please provide your thoughts

**Comment by terrycullen** [comment]
and does FHIR pull over whatever is in the test field result? how does that get normalized for CDS?

**Comment by jennifershivers** [comment]
@jamlung-ri for now, I will put the FHIR mappings on there.  @brynrhodes @SeanWheelwright please advvise on how to put this in the DD

**Comment by jennifershivers** [comment]
re: "and does FHIR pull over whatever is in the test field result? how does that get normalized for CDS? " - I think clinical decision support needs to write queries that look for a lab test X with a result of X.  FHIR is just the standard structure that will be used by the clinical decision support logic.

**Comment by terrycullen** [comment]
I agree and that is what most CDS does--but we need to make sure that FHIR pulls the RIGHT data over and puts it in the right field for the CDS to act upon.. this is such difficult work- the CDS part of this.
