### ISSUE TITLE
2114: Date of Last Cervical Cancer Screen 

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#47]
@terrycullen asks:

Is this ALL cervical cancer screens?

Can we verify this with a clinical SME?

Reference: [ID 2114](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by jennifershivers** [comment]
We can find lots of codes for cervical cancer screening.  Is there a specific one that we need to use?
LOINC	Name	R/O/C	Cardinality	Example UCUM Units
86662-4	Pap smear tests - FPAR 2.0 set			
 Indent10524-7	Microscopic observation [Identifier] in Cervix by Cyto stain			
 Indent18500-9	Microscopic observation [Identifier] in Cervix by Cyto stain.thin prep			
 Indent19765-7	Microscopic observation [Identifier] in Cervical or vaginal smear or scraping by Cyto stain			
 Indent19766-5	Microscopic observation [Identifier] in Cervical or vaginal smear or scraping by Cyto stain Narrative			
 Indent19774-9	Cytology study comment Cervical or vaginal smear or scraping Cyto stain			
 Indent33717-0	Cytology Cervical or vaginal smear or scraping study			
 Indent47527-7	Cytology report of Cervical or vaginal smear or scraping Cyto stain.thin prep			
 Indent47528-5	Cytology report of Cervical or vaginal smear or scraping Cyto stain			
 Indent19762-4	General categories [Interpretation] of Cervical or vaginal smear or scraping by Cyto stain			
 Indent19764-0	Statement of adequacy [Interpretation] of Cervical or vaginal smear or scraping by Cyto stain

**Comment by jamlung-ri** [comment]
This term was removed from the data dictionary since it was not needed for the STI Screening profile.
