### ISSUE TITLE
Content Clarification - "Facility can accommodate?"

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#5]
ID 1786 of the [Master Data Dictionary](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us/edit?usp=sharing) has no Data Element Label. Because it has True/False input options and sits in the Activity ID "Facility can accommodate?", however, I assume that this row is meant to answer the Activity ID question. Is this correct?

**Comment by natschja** [comment]
I think this is a question for Jenny - I would assume the same, but would ask her to verify

**Comment by jennifershivers** [comment]
@jamlung-ri Did you send this to Jenny?

**Comment by jamlung-ri** [comment]
Nope, sorry. I thought @natschja was doing it, but I never explicitly communicated that. Nat, can you make sure Jenny sees this? Thanks!

**Comment by natschja** [comment]
Sure - will look out for this in the updated data dictionary once I get this.
