### ISSUE TITLE
2155: Screenings performed

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#50]
This data element has the following input options:

- Herpes simplex viruses screen

- Human papillomavirus screen

- Trichomoniasis screen

- Chlamydia screen

- Gonorrhoea screen

- HIV test

- Syphilis screen

There may be a modeling issue to discuss. 

Reference: ID 2155

**Comment by jennifershivers** [comment]
It seems like the question is "what screenings were performed"  however the DD seems to state that only one option can be selected.  I would assume that multiple screenings would be done?  Seems like this is a question for Nat

**Comment by jamlung-ri** [comment]
@natschja Thoughts?

**Comment by jennifershivers** [comment]
This needs to be an extension but I am not sure what existing resource would be extended.

**Comment by terrycullen** [comment]
is the screening the. code for the LAB TEST? or something else ; and, JS is right; most times, the screening has been for many things

**Comment by jennifershivers** [comment]
coded to Observation.code and then each one below is a screening that was done.
