### ISSUE TITLE
gtin - Medication.code or Medication.identifier

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#51]
Medication.code or Medication.identifier

The FHIR specification notes that gtin can be either (see https://www.hl7.org/fhir/terminologies-systems.html).  Are there any ramifications to choosing one or the other?  If we are searching for identifiers for decision logic purposes, a search should look in both .code and .identifier.  

@brynrhodes @docpaul

**Comment by brynrhodes** [comment]
In general, codes are used for "types" where identifiers are used for "instances", so if the Medication is literally identifying a Medication instance in stock, it would have an identifier, but if it's identifying a type of medication in a catalog, or the type of medication for a prescription (I think the more prevalent use case for our purposes), then it would be a code. We should identify the most appropriate item for our usage and stick with that.

**Comment by jennifershivers** [comment]
Because it was the medication being dispensed, I put it in the identifier.
