### ISSUE TITLE
Form Code duplicated in DD?  

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#52]
#2238 has "drug form" with input options 

#2272 has "form-code" with no input options 

Proposal  
1. Determine if the list needs to be expanded to support both STI and FP
2.  get rid of "form-code"  (duplicate entry)  

Other option is to make specific form lists for each medical specialty (STI, FP, HIV etc)

**Comment by jamlung-ri** [comment]
form_code was removed from the data dictionary, so no further action is needed.
