### ISSUE TITLE
FHIR modeling for Free text description of "other"

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#53]
What do we do with 1902 and 1943?  There are a lot of these in the dictionary.  

We need to figure out how to model the "other (specify)" input options

**Comment by brynrhodes** [comment]
In #28 I suggested we should define an "other" code in the core IG. We can use that as the indicator that an input option of this type is available. When providing data, the `text` element of the CodeableConcept can be used to provide the user-entered value.

**Comment by jamlung-ri** [comment]
Thanks Bryn. @jennifershivers See ID 1901-1902 for an example of how I used this.

**Comment by jennifershivers** [comment]
got it.
