### ISSUE TITLE
1867 & 1662-1675: Vasectomy

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#54]
Trying to understand what the Vasectomy field is alluding to. Is the question asking "For males who want a vasectomy, what previous issues should be considered before performing the procedure?". 

Here are the terms in question with their respective IDs:

1867 | Vasectomy
-- | --
1662 | Coagulation disorders
1663 | Previous scrotal injury
1664 | Systemic infection or gastroenteritis
1665 | Large varicocele
1666 | Large hydrocele
1667 | Filariasis
1668 | Elephantiasis
1669 | Intrascrotal mass
1670 | Cryptorchidism
1671 | Inguinal hernia
1672 | Scrotal skin infection
1673 | Balanitis
1674 | Epididymitis
1675 | Orchitis

[DD Link](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by jennifershivers** [comment]
Made this a UI element and the items under it are conditions.
