### ISSUE TITLE
Family Planning - Reason for Visit/family Planning -  "Issues and Concerns"

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#55]
@terrycullen can we map this if we look for "Contraception Concerns" or "Contraception Issues" ?    (see row 1368)

**Comment by terrycullen** [comment]
trying to see; but it is funny. I was searching and it brought me to an IHS document that we did a long time ago...https://www.ihs.gov/sites/ehr/themes/responsive2017/display_objects/documents/patches/SNOMEDCTandIPL_FAQs.pdf
about SNOMED mapping; more to come

**Comment by terrycullen** [comment]
Z30 Encounter for contraceptive management NON-BILLABLE
Z30.0 Encounter for general counseling and advice on contraception NON-BILLABLE
BILLABLE Z30.2 Encounter for sterilization
Z30.4 Encounter for surveillance of contraceptives NON-BILLABLE
BILLABLE Z30.8 Encounter for other contraceptive management
BILLABLE Z30.9 Encounter for contraceptive management, unspecified
one of these> ICD 10?

**Comment by terrycullen** [comment]
maybe we can use Z30.. let me keep looking

**Comment by terrycullen** [comment]
general rule
default to the higher level (not otherwise specified) of code that should include the concept  if unable to find the specific term

**Comment by jamlung-ri** [comment]
> general rule
> default to the higher level (not otherwise specified) of code that should include the concept if unable to find the specific term

Regarding this, I put this general rule into the [SOP](https://docs.google.com/document/d/10vLBX0bE7a3x4QCYE1TkhNwAOgoyjVSwA3yYsYAdHlg).

**Comment by jennifershivers** [comment]
@jamlung-ri Thanks!  That means we also need to put in a comment about use into the FHIR Implementation guide / or page about the WHO FHIR guides.  For using for querying, one may want to consider using the higher level term to find child terms if using this for decision logic.  @brynrhodes
