### ISSUE TITLE
spreadsheet structure for repeated items 

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#56]
For items like family planning methods, which are the answer set for several questions, do we need to repeat thses in the spreadsheet? 
(I assume the answer is yes.  
I also assume that they can have the same ID @jamlung-ri ?)

See 1688 where there is just a designation to to have the family planning methods in there.

**Comment by jamlung-ri** [comment]
They cannot have the same ID, but we could add rows and assign them new IDs very easily; the mappings and other details can just be copied from the original row.

**Comment by jennifershivers** [comment]
Once we move to a tool that can publish a value set that can be used with multiple questions, we would want to be able to re-use the value set.  For now, let's duplicate and then we can resolve this when the dd is moved to a tool like OCL.  

@jamlung-ri do you want to start adding the rows for the repeated list of family planning methods?  We can close this when it is done.

**Comment by jamlung-ri** [comment]
The following rows were added to the spreadsheet: 2320-2345

The content for these rows were copied from the following existing rows in the spreadsheet: 1287-1288, 1291-1292, 1294, 1296-1298, 1300-1314, 1852-1859
