### ISSUE TITLE
proposal for modeling medical history in the spreadsheet

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#58]
For items like 1420 "History of hypertension"  the decision logic would need to search for any instance of Condition.code = 99999 for hypertension code anywhere in the patient's list of complaints or diagnosis regardless of status.   

However, when we met with Nat on Friday, we discussed creating an input option for "patient history of" and then input options for the history codes to pick from .  I think all we actually need to do is to state what the Condition.code is for that clinical concept?  

However teh items in the spreadsheet are true/false.

**Comment by jennifershivers** [comment]
or we do create a high level DATA ELEMENT of Historical Conditions with Condition.category = encounter-diagnosis and INPUT OPTIONS that are mapped to FHIR Condition.code

**Comment by terrycullen** [comment]
I think that you use the fair for history of and then you use diagnostic code for the condition (assuming that it is a diagnosis); there may also be family history of... and then a diagnosis.. that is how SNOMED would do family and history of.. the issue will be determining what is meant by history of (not active problem or just meaning diagnosed in the past and still active). we should figure out what the plan is for use of this information,
