### ISSUE TITLE
Content Clarification - "Level of urgency for the referral"

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#6]
Master ID 1799 of the [Master Data Dictionary](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us/edit?usp=sharing) indicates that, because it is multiple choice, there should be input options. Should there be input options in the list?

**Comment by natschja** [comment]
There should be...this would also be a question for Jenny, but it might already be addressed in her newer version

**Comment by jamlung-ri** [comment]
@natschja Just an update on this, the newer data dictionary does not address this. Should we take it to Jenny for clarification? I included details of the row below.


Activity ID | Data Element Code (STI) | Data Element Code (FP) | Data Element Label | Data Element Name | Description | Data Type | Multiple Choice | Input Options
-- | -- | -- | -- | -- | -- | -- | -- | --
4.8 Fill out referral details | ST.DE.071 | FP.DE.093 | Level of urgency for the referral |   | Indicate if it is an urgent referral. | Coding |   | Select One

**Comment by jamlung-ri** [comment]
Jennifer was able to find a FHIR value set that satisfies this. http://hl7.org/fhir/ValueSet/request-priority
