### ISSUE TITLE
Extension Needs - For discussion with DCG

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#60]
We have come across multiple types of situations that we need to be able to handle:  

### 1.  Extensible Binding (Level 1)
Adding a code to an extensible FHIR value set.  For example, if a diagnosis is not in the http://hl7.org/fhir/ValueSet/condition-code list, additional diagnosis codes would be added to the value set.

**- Question about this one - what if the value set uses SNOMED and we want to use ICD?** 

Probably need to specify:  

- code list 
- code to add
- dictionary (SNOMED, ICD-10) 

### 2.  Add Element (Level 2) 
Additional FHIR Element is needed for an existing resource. This is when an attribute like _"Facility Catchment Population"_ is not handled by the core FHIR  _HealthcareService_  FHIR resources.  

Need to specify the following columns:  

- "HL7 FHIR R4 - Resource" - Fill in the new element name and path (e.g. HealthcareService.Catchment)
- "Required" - Follow WHO's format
- "Data Type" - Follow WHO's format
- "Multiple Choice" (if applicable) - Follow WHO's format
- "Input Options" (if applicable) - Follow WHO's format

### 3.  Create resource (Level 3) 
Creating a new resource should be avoided where possible. This is a significant time investment and may not be necessary to map the term to FHIR. Getting creative with data modeling and leveraging existing FHIR resources is the most preferred method.

**Comment by jamlung-ri** [comment]
I will update the ticket description as appropriate, but here is a quick summary of my conversation with DCG today:

- "Extension" has a specific meeting in FHIR, so we should work to ensure we are using clear wording from now on. In particular:
    1. Instead of "Add Code", we should call this "Extensible Binding" 
    1. Instead of "Add Attribute", we can call this "Add Element".

- Our third case, "Create Resource" is something that should be avoided in this project. Creating a new resource is a significant time investment. Extreme preference should be given to "Add Element", and we can adjust the data modeling to better fit within FHIR's existing resources.

- To designate an extension in our data dictionary for the tooling to accept, we can simply title the new element in the "HL7 FHIR R4 - Resource" column. The tool will know if the element does not already exist in FHIR. 
    - As for designating cardinality, terminology binding, etc., we can simply specify the following columns in the data dictionary, following the same format as WHO followed:
        - Required
        - Data Type
        - Input Options (if applicable)
