### ISSUE TITLE
Reason Contact Not Made 

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#61]
### Background  - 2291 (STI Tab) Reason Contact not made  

Issue - no code list specified by WHO, but there are two elements 2288 and 2289 which are reasons.  

FHIR reasons for communication not made - http://hl7.org/fhir/ValueSet/communication-not-done-reason

Code | Display | Definition
-- | -- | --
unknown | Unknown | The communication was not done due to an unknown reason.
system-error | System Error | The communication was not done due to a system error.
invalid-phone-number | Invalid Phone Number | The communication was not done due to an invalid phone number.
recipient-unavailable | Recipient Unavailable | The communication was not done due to the recipient being unavailable.
family-objection | Family Objection | The communication was not done due to a family objection.
patient-objection | Patient Objection | The communication was not done due to a patient objection.

### Background - Patient Follow up 

1819 "Reason not contacted if client had given consent to be contacted"

It does have input options:  

1826 | Contact information is no longer valid
-- | --
1827 | Client has moved from the service area
1828 | Client asks to not be contacted again.
1829 | Client deceased.

### Full recommendations:  

1.  Extend the FHIR reasons for communication not made - http://terminology.hl7.org/CodeSystem/communication-not-done-reason (Core extension) and use for both (STI and follow up) code lists

- Contact no longer valid 
- Moved from service area
- Deceased

2.  Map WHO reason "asks not to be contacted" to FHIR "The communication was not done due to a patient objection"

3.  Remove DD terms below as these are duplicate to the reason list provided by FHIR.  (see above) 

1809 | Error received
-- | --
1810 | Error message

Also remove 1811 which is "Reason Contact Not Made"  which appears to be a duplicate of #1819
- Remove 2288 Error Received 
- Remove 2289 Error Message

**Comment by jennifershivers** [comment]
@jamlung-ri let's proceed with this proposal.

**Comment by jamlung-ri** [comment]
Done
