### ISSUE TITLE
 Questions about diagnosis vs 2179 STI Treatment recommendation

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#62]
Questions about diagnosis 2131 vs 2179 STI Treatment recommendation

1.  They both model to the FHIR "condition" resource.  However one, diagnosis, has been officially diagnosed and the other has not been diagnosed via a diagnostic test, but the care giver will be treating for it.    @terrycullen @docpaul can you check this assumption?  If that is the case then the only difference between these two is the verification status of the condition (

unconfirmed \| provisional \| differential \| confirmed \| refuted \| entered-in-error)  

2. We can just go ahead and code these to the FHIR "condition" resource or we can create a WHO specific profile for STI conditions.  I don't think either is wrong.  Which approach is most useful?

**Comment by jamlung-ri** [comment]
@jennifershivers You put 2031, but do you mean 2003? 2003 is the question (Reported symptoms), while 2031 is one of its input options.

**Comment by terrycullen** [comment]
unclear how the verification can be evaluated based on data in a HIT system; POV and diagnosis is a diagnosis, not a possible/. differential/ unconfirmed.. those adjectives are NOT normally included in a POV or PL.. I am not clear what to do with this-perhaps there is a questionnaire that they are referring to? need WHO SME

**Comment by jamlung-ri** [comment]
We mapped diagnoses to the Condition resource in FHIR, and we mapped STI Treatment Recommendations to the CarePlan Activity reasonCode resource.
