### ISSUE TITLE
FHIR Mapping for History of a Condition

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#63]
The data dictionary has multiple terms for medical history. In FHIR, medical history is mapped to the Condition resource, but I am unsure of what is the best way to designate this condition as part of the medical history, rather than an active problem.

Within the Condition resource, there are some potentially useful resources:

- clinicalStatus (active | recurrence | relapse | inactive | remission | resolved)

- category (problem-list-item | encounter-diagnosis)

- abatement (Date, age, etc. when the condition went into resolution/remission)

**Which, if any, of the above resources should we use to designate historical issues?** I think clinicalStatus would be the best, but which status we choose may be dependent on the condition (e.g. heart issue could be resolved, whereas high blood pressure could be in remission).

Example terms:

- 1429 - History of hypertension

**Comment by brynrhodes** [comment]
The only reference I can find in the FHIR spec to "History of X" is in this [discussion](http://hl7.org/fhir/condition.html#9.2.3.3) for Condition. It feels confusing to me to model it that way though, if it's just a "History of X" that feels much more like an Observation to me. (What would be the prevalence period for "History of X"? If it's from the time the "condition" is recorded to the end of time, that seems like it would be way too likely to be potentially confused with an actual Condition, rather than a historical one)

**Comment by bmamlin** [comment]
FHIR doesn't have a good place for Past Medical History (PMH), in my opinion. For now, FHIR gives PMH as the [first example of using questionnaire](https://www.hl7.org/fhir/questionnaire.html). So, the best option at this time is probably a `QuestionnaireReponse` where the question is [SNOMED 417662000](https://browser.ihtsdotools.org/?perspective=full&conceptId1=417662000&edition=MAIN/2019-07-31&release=&languages=en) and the answer is the specific condition as another SNOMED code.

Questionnaires may make this overly complicated, so an alternative approach would be to use an `Observation` resource.

**Comment by brynrhodes** [comment]
Given this discussion I would recommend using an Observation resource and noting this discussion in the methodology documentation for "Past Medical History". Agree that Questionnaires would make this overly complicated.

**Comment by jamlung-ri** [comment]
Thanks for the discussion everyone! We will follow Bryn's recommendation to map these to Observation resources.

**Comment by jennifershivers** [comment]
Decision - We will follow the FHIR guidance and map to a Condition.  Where possible, we will code to the term that includes "history of condition"
