### ISSUE TITLE
Split into two rows: 1460, 1463-1464 - Deep venous thrombosis (DVT)/Pulmonary embolism (PE)

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#64]
@terrycullen requests that Deep venous thrombosis (DVT)/Pulmonary embolism (PE) and any other combined DVT/PE terms should each be separated into two rows in the data dictionary.

@natschja Can you approve of this change?

Reference: [ID 1460, 1463-1464](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by jennifershivers** [comment]
RI recommends splitting these because it is recorded as a FHIR condition and there are two different codes for these conditions.

**Comment by jennifershivers** [comment]
128053003 snomed  DVT; SNOMED. 59282003 PE

**Comment by jamlung-ri** [comment]
These have been split. See Structural Change Tracking tab for details.
