### ISSUE TITLE
1581 - Tuberculosis

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#67]
@terrycullen asks:

Active, or history of tuberculosis?

Reference: [ID 1581](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by natschja** [comment]
As part of the MEC guidance https://apps.who.int/iris/bitstream/handle/10665/181468/9789241549158_eng.pdf Have added this to the list of questions for experts

**Comment by jamlung-ri** [comment]
This term was regarded as a UI element and was thus removed from the Implementation Guide.
