### ISSUE TITLE
1645 - List of NRTIs

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#68]
@terrycullen asks:

can we get the list (of NRTIs) that they want us to use?

Reference: [ID 1645](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by terrycullen** [comment]
this is also a larger issue-it applies to the 'drug classes'-- since I. am unclear of the use of this in CDS, I am unclear how to map this

**Comment by jamlung-ri** [comment]
This was mapped to an RxNorm class code.
