### ISSUE TITLE
Modeling 2195 - Postpartum infection

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#71]
For 2195 - Postpartum infection, @terrycullen requests that the mapping should be any infection that occurs during the postpartum state. How can we model this using FHIR?

**Comment by brynrhodes** [comment]
If I'm understanding correctly, I'd suggest using a calculation expression, so the existence of an infection in a given time frame would result in a true for this element.

**Comment by terrycullen** [comment]
if that is what is meant; we need to clarify if this is specific for postpartum endometritis OR any post partum infection ( need WHO SME to comment)

**Comment by jamlung-ri** [comment]
@natschja Do you have any input on Terry's question?

**Comment by jennifershivers** [comment]
@brynrhodes is this CQL and not really part of the FHIR mapping?  I'm still unsure what to do with this.

**Comment by jamlung-ri** [comment]
We modeled this as a reasonCode in FHIR.
