### ISSUE TITLE
1475-1481: Mapping Risk Factors in FHIR

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#73]
What is the best way to model a risk factor in FHIR? Because of the mix of input options for a risk factor (e.g. Cardiovascular Risk is based on conditions like Stroke, observations like Obesity and Smoking status, and others like Cardiovascular Risk Due to Age.

Options:

1. The simplest way would be to map it as an observation.

1. FHIR also has a RiskAssessment resource, although it is focused on the event that determined the risk factor, rather than the risk factor itself.

1. Others?

**Comment by bmamlin** [comment]
FHIR would probably collect risk factors as `QuestionnaireResponse`s or as `Observation`s. The score (e.g., cardiac risk score) would be an `Observation`. There are several [examples of these in LOINC](https://search.loinc.org/searchLOINC/search.zul?query=risk+score).

Many of these are pubic domain, but some validated instruments/calculators are copyrighted (for example, the [Opioid Risk Score](https://loinc.org/91392-1/) is copyrighted). I would assume WHO would only be using public domain instruments, but it's worth checking for this detail when using a LOINC term for an instrument like this.

**Comment by brynrhodes** [comment]
I'd suggest RiskAssessment since it gives more detailed elements related to risk assessments specifically.

**Comment by jamlung-ri** [comment]
If we were to use the RiskAssessment resource, then I think we would need to modify the resource a bit so that we can input the risk factors. Currently, the only outcome resource appears to be RiskAssessment.prediction, which must have a probability (as a percentage) attached to it. Since I don't think WHO wants to use probabilities here, maybe we could Add an Element to the RiskAssessment resource like "RiskAssessment.risksPresent", which would represent each of the risks factors that are present that contribute to Cardiovascular risk.

@bmamlin @brynrhodes @jennifershivers Thoughts?

**Comment by bmamlin** [comment]
I believe [`RiskAssessment.basis`](https://www.hl7.org/fhir/riskassessment-definitions.html#RiskAssessment.basis) is meant to reference the data (e.g., observations) used for the assessment. In other words, `RiskAssesment` is modeled to reference instead of directly include the data used for the calculation. One option would be a bundle that includes the observations (questions & answers) used to calculate the risk and a `RiskAssessment` to represent the score.

If the risk score cannot be expressed as a percentage (i.e., a coded value instead of a number), then you'd use [`RiskAssessment.prediction.qualitativeRisk`](https://www.hl7.org/fhir/riskassessment-definitions.html#RiskAssessment.prediction.qualitativeRisk) to provide a concept code for the likelihood.

**Comment by terrycullen** [comment]
?I worry about any of these options given that we need to then propose that the deployment and use of any CDS has 'requirements' to deploy a data-- Burke, is that correct?

________________________________

**Comment by terrycullen** [comment]
to clarify my comment-- there would need to be agreement on the risk assessment tool (presumable vetted) and the inclusion of the components of the assessment.. and then a score (which I assume COULD be a number/percentage). however, as we know, there are multiple assessment tools that are used for risk assessment--and I must assume that after calculated, these scores will be used for some CDS algorithm.. This gets messy very quickly. we COULD model this as a 'process' but I dont know what to do with the SPECIFICS of a risk assessment

**Comment by brynrhodes** [comment]
Given this discussion, I'd recommend we model Risk Factors as Observations, potentially with appropriate profiles referencing input data that is the basis for the Risk Factor. Also recommend we capture this discussion in the methodology as a Risk Factors and Assessments topic.

**Comment by jamlung-ri** [comment]
Thanks for the discussion everyone! We will move forward with Bryn's recommendation to map risk factors to Observations. However, there are connotations related to terminology mapping when it comes to risk factors, which we should document. Specifically, some terminology codes are tied to a questionnaire or assessment tool in LOINC, so we will want to find a way to use codes that are not tied to those. That can include either finding another code or adding that term to a list of potential additions to the terminology standard.
