### ISSUE TITLE
Inferences in the Data Dictionary

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#77]
Based on the discussion from our meeting and from Bryn's suggestion in [Ticket 74](https://github.com/who-int/Data-Dictionary-Mapping/issues/74), we will be noting inferences for certain situations. 

@brynrhodes We will want to come up with a way to reflect these inferences in the data dictionary so that Jennifer and I can understand how best to map those to FHIR.

**Comment by jennifershivers** [comment]
Seems like 1491 would be a calculation done in the interface?

**Comment by jennifershivers** [comment]
Example is done in the spreadsheet in row 1491.

**Comment by sliver007** [comment]
@brynrhodes We're looking for some specific guidance on how to represent "inferences" in the modeling. A proposed solution that we discussed on today's call (an example is done in the spreadsheet on row 1491 as Jennifer noted):
- Put the formula in Column AL (HL7 FHIR R4 - Additional FHIR Mapping Details) - Condition.onset[x].onsetDateTime = today() - 20 years
- Put the condition in Column B - "Diabetes > 20 years duration"

Feedback on that or guidance in a better direction?
