### ISSUE TITLE
Assumption - No codelist needed for State etc

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#8]
I'm making an assumption that there will be no code list needed for "state" which is also defined as a province / territory in FHIR and there will be no code list for "postal code" as these vary by country.  FHIR says a code list can designated with an extension, but I don't think we want to do that as it needs to support multiple countries.  

Let me know if you disagree @terrycullen @jamlung-ri 

See rows 1724 and 1725

**Comment by terrycullen** [comment]
I agree

Maybe we should not that there is an ansi standard code set so a country may have their own code set.

**Comment by jamlung-ri** [comment]
I agree. We should leave this one open-ended. I don't think any further action is needed.

**Comment by jennifershivers** [comment]
![Screen Shot 2019-12-12 at 9 32 01 AM](https://user-images.githubusercontent.com/13437212/70720734-5b58c980-1cc2-11ea-9d2e-d979ae7829cd.png)

**Comment by jennifershivers** [comment]
Close issue
