### ISSUE TITLE
1445 - Contraception Method requested

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#80]
For [ID 1445](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us), the data type is Boolean, but this seems like it should be a Multiple Choice question, with the contraceptive methods as input options. Can we change the data type for this term, or are we misunderstanding it?

For context, ID 1444 above it is "Contraception Method in mind", which asks if the patient came in with the desire to use a specific contraceptive method.

**Comment by jamlung-ri** [comment]
Given the description of this data element ("The first pick of method desired by the client, prior to medical eligibility tests. This may be the method in mind or the method selected after discussing the full range of methods."), I will assume that this should actually be a multiple choice data element, with the Contraceptive methods that were defined in other parts of the data dictionary. I will make the appropriate changes to the data dictionary.

**Comment by natschja** [comment]
Should be multiple choice or "coding" will send update

**Comment by jamlung-ri** [comment]
This has been addressed in the data dictionary.
