### ISSUE TITLE
Implied Resource Creation - Devices and Medications

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#83]
When we are mapping to a resource that references another resource, do we need to define anything in the data dictionary so that the tool will automatically create the referenced device or medication?

Example: ID 1286 - "Device-based Birth control method reported at intake" is being mapped to the `DeviceUseStatement.device.type.coding.code` resource. This implies that the patient is using a specific device. However, the data dictionary itself does not create the device resource for this, so the implication is that one will be created, using the terminology code provided.

Thoughts? cc: @jennifershivers

**Comment by jennifershivers** [comment]
Notes from today:  
Example: MedicationStatement.medication[x].medicationReference.code
Only need to know the target down through the chosen type, i.e. MedicationStatement.medication[x].medicationReference.
What we have after the x should be going in the Base Profile column
Observation.value[x] in Resource column, then Quantity, CodeableConcept, etc. in the Base Profile column
For Extensions, add a column for Extensions
