### ISSUE TITLE
Duplicate rows?  Date of abortion or miscarriage?

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#85]
Both 1989 and 2002 are in the current STI DD.  Recommend deleting one of them OR making one the date for miscarriage and one the date for abortion.  This may be on the screen more than once if there are multiple miscarriages or abortion.   

1989 | Date of miscarriage or abortion
2002 | Date of abortion or miscarriage

@jamlung-ri @natschja

**Comment by jennifershivers** [comment]
Proposal - split into "date of miscarriage" and "date of abortion"  as these are two distinct codes.   
@natschja @terrycullen @jamlung-ri

**Comment by jamlung-ri** [comment]
Just a note: this affects ID 1339 - "Miscarriage or abortion stage of pregnancy" too.

**Comment by jennifershivers** [comment]
We will leave them together, but need to reduce to one entry and re-word them to be the same.

**Comment by jennifershivers** [comment]
@jamlung-ri can you merge these two?  This is the one that is still in the FP DD.  I so not see the other one.

**Comment by jamlung-ri** [comment]
IDs 1989 and 2002 have been merged into ID 1351.
