### ISSUE TITLE
1859 - Combined injectable contraception

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#89]
@terrycullen says "Not clear what medication this is" for ID 1859 - Combined injectable contraception.

Is this a class of medication or a specific medication?

**Comment by natschja** [comment]
CICs weren't part of the finalized list of contraceptive methods to be included - it should have been taken out. but will confirm if this should still be included, and if so, what the specific medication is

**Comment by jamlung-ri** [comment]
CICs are not featured very well in many resources, so this is not a high priority method. Not widely available in the public sector. Don't have good information on how available it is. It's not a common global method, but it could be part of the formulary for a government. It's pitched towards private sector, but even so, it's not widely offered. Usually using patch or vaginal ring instead. This is a very low priority method, so perhaps it does not need to be in the accelerator kit right now. Nat will leave it out of the accelerator kit. No need to map.

**Comment by jamlung-ri** [comment]
This was placed in the Extended Content code system, and should be placed in consideration for adding into a terminology standard.
