### ISSUE TITLE
Drug Form - use WHO specific list or use more comprehensive FHIR list?  

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#91]
WHO list 

2238 | Drug form
-- | --
2239 | gel
2240 | compound tincture of benzoin
2241 | oral
2242 | vaginal suppository
2243 | intramuscular
2244 | vaginal tablet
2245 | eye ointment
2246 | intravaginally
2247 | vaginal tablet
2248 | cream
2249 | Vaginal cream
2250 | solution

FHIR list  - http://hl7.org/fhir/ValueSet/medication-form-codes

@natschja Is there a specific reason to use the WHO list provided in the dictionary? It may be better to just default to FHIR's drug form list.

**Comment by jamlung-ri** [comment]
The custom valueset was used for this, rather than using FHIR's drug form list.
