### ISSUE TITLE
DD Accuracy - Description and Name for 1879 do not seem to match

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#93]
1851 | Number of births (The number of pregnancies reaching parity.)
-- | --
1879 | Number of births (The number of pregnancies reaching parity or nulliparity)

When reviewing for consistency, the description and the data element name for 1879 do not seem to be consistent.  Does the name or the description need to change?

**Comment by jennifershivers** [comment]
The definition of the same field is different for FP and STI.

**Comment by jamlung-ri** [comment]
These rows were consolidated into a single term.
