### ISSUE TITLE
FHIR Mapping for 1350 - Pregnancy test available

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#94]
For 1350 - "Pregnancy test available", what is a good way to map this to FHIR? Is this a characteristic of the facility? Is this an Observation (i.e. "No pregnancy tests available")?

**Comment by jennifershivers** [comment]
I have another ticket where I am asking about facility characteristics https://github.com/who-int/Data-Dictionary-Mapping/issues/59.  I think we need to ask if this is pertaining to the facility.  It seems that observations can pertain to other objects besides patient.  But we would want to specify this correctly.  @natschja

**Comment by terrycullen** [comment]
I think that it is a facility. characteristic. (not that you asked me!)
