### ISSUE TITLE
1426 - Injection cycle

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#95]
@terrycullen or @natschja Do you know what this term means? I might just need a different explanation to understand how to map this to FHIR.

**Comment by terrycullen** [comment]
I believe that it is the time cycle for use of what are called depo injections for family planning
so, is it prescribed every three months?

**Comment by jamlung-ri** [comment]
Related SNOMED codes that Terry posted: 

medications. not taken. Drugs not taken/completed (situation) {266710000 , SNOMED-CT }
       Parent/Child (Relationship Type)
Drug discontinued - patient fear/risk (situation) {182871005 , SNOMED-CT }
Drug discontinued - reason unknown (situation) {182870006 , SNOMED-CT }
Drug discontinued - too expensive (situation) {182872003 , SNOMED-CT }
Drug not taken - dislike form (situation) {182863006 , SNOMED-CT }
Drug not taken - dislike taste (situation) {182862001 , SNOMED-CT }
Drug not taken - inconvenient (situation) {182865004 , SNOMED-CT }
Drug not taken - pat disbelief (situation) {182867007 , SNOMED-CT }
Drug not taken - patient lost tablets (situation) {182869005 , SNOMED-CT }
Drug not taken - problem swallowing (situation) {266711001 , SNOMED-CT }
Drug not taken - side-effects (situation) {182864000 , SNOMED-CT }
Drug treatment stopped - patient ran out of tablets (situation) {182873008 , SNOMED-CT }
Treatment stopped - alternative therapy undertaken (situation) {182868002 , SNOMED-CT }
Treatment stopped - patient unable to concentrate (situation) {182874002 , SNOMED-CT }

**Comment by natschja** [comment]
I don't think this is in the new data dictionary. I've tried to find how the injection cycle would be relevant to issues and concerns, and I was unable to find it in any of the guidance documents. I'll add this to the list of questions for experts - but my feeling is that this data element would be taken out.

**Comment by jamlung-ri** [comment]
Issue of injection timing and late injection. Relates to "Has anyone had any problems with use? Headaches, bleeding, BP?" There is also FPR guidance on this, "What happens if a woman comes in early? Can injections be given up to 2 weeks early?" There is a period of 2 weeks where an injection can still be given.

What would you call a late injection? Not a diagnosis.

**Comment by jamlung-ri** [comment]
This was removed from the data dictionary, so no further action was needed.
