### ISSUE TITLE
UTI Terminology coding alignment? 

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#96]
![Screen Shot 2020-02-10 at 2 56 29 PM](https://user-images.githubusercontent.com/13437212/74184956-ba30b580-4c15-11ea-8791-b43eeac6e71f.png)

@terrycullen should these UTI terms be coded the same?  It looks like there are some slight differences.

**Comment by terrycullen** [comment]
these are all UTI; so, the value set would be all of them; I would make them all the same (with all of those codes). thanks for finding that

**Comment by jamlung-ri** [comment]
I made the change in the data dictionary. All of these terms now have ICD-10 codes N39; Z87.440 and SNOMED code 68566005.
