### ISSUE TITLE
duplicates but coded differently?

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#97]
<img width="1218" alt="Screen Shot 2020-02-11 at 9 56 00 AM" src="https://user-images.githubusercontent.com/13437212/74248023-f7985000-4cb4-11ea-82d0-88491765c787.png">
These two terms seem like they are duplicates but they are coded to different terms.  @terrycullen @docpaul please advise.

**Comment by terrycullen** [comment]
Disorder of gallbladder (disorder) {39621005 , SNOMED-CT }
       Parent/Child (Relationship Type)
Abscess of gallbladder (disorder) {32038009 , SNOMED-CT }
Adenomyomatosis of gallbladder (disorder) {721723003 , SNOMED-CT }
Adhesion of gallbladder (disorder) {13516000 , SNOMED-CT }
Aplasia of gallbladder (disorder) {253806000 , SNOMED-CT }
Atony of gallbladder (disorder) {287326003 , SNOMED-CT }
Atrophy of gallbladder (disorder) {64664008 , SNOMED-CT }
Biliary dyskinesia (disorder) {197432008 , SNOMED-CT }
Cholecystitis (disorder) {76581006 , SNOMED-CT }
Cholesterolosis of gallbladder (disorder) {61565001 , SNOMED-CT }
Congenital disorder of gallbladder and biliary tract (disorder) {235913009 , SNOMED-CT }
Dyskinesia of gallbladder (disorder) {721721001 , SNOMED-CT }
Fistula of gallbladder (disorder) {16957005 , SNOMED-CT }
Gallbladder calculus (disorder) {235919008 , SNOMED-CT }
Gallbladder mass (disorder) {138561000119104 , SNOMED-CT }
Gangrene of gallbladder (disorder) {111372003 , SNOMED-CT }
Hemocholecyst (disorder) {95560005 , SNOMED-CT }
Hydrops of gallbladder (disorder) {47312008 , SNOMED-CT }
Hypertrophy of gallbladder (disorder) {76875008 , SNOMED-CT }
Injury of gallbladder (disorder) {262805007 , SNOMED-CT }
Intramural calcification of gallbladder (disorder) {110995008 , SNOMED-CT }
Nonfunctioning gallbladder (disorder) {80527006 , SNOMED-CT }
Obstruction of gallbladder (disorder) {75726005 , SNOMED-CT }
Occlusion of gallbladder (disorder) {197416005 , SNOMED-CT }
Poorly functioning gallbladder (disorder) {289999003 , SNOMED-CT }
Rupture of gallbladder (disorder) {22788004 , SNOMED-CT }
Stenosis of gallbladder (disorder) {38712009 , SNOMED-CT }
Ulcer of gallbladder (disorder) {59612001 , SNOMED-CT }

snomed list with the 39 code as the parent
the first code in the sheet is HISTORY of GB disease

once again, we may want to create a value set and include both of the codes in the sheet above (and then consider if you want to include all of these other SNOMED codes for the value set)... but, they are both right, so you need to at least include the two of them

**Comment by jamlung-ri** [comment]
Both codes are now in the SNOMED field. I am closing this, but feel free to reopen if more discussion is needed.
