### ISSUE TITLE
Running Log of Post-Project Recommendations

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#98]
In plenty of conversations, we have identified issues related to this project that should be addressed, but it is not in the scope of this project. Please use this ticket to log these recommendations, issues, etc. I will attempt to update this ticket with concerns that come up during project meetings or in Slack chats.

**Comment by jamlung-ri** [comment]
Precision of naming of terms throughout the data dictionary is a key issue that must be addressed as early as possible, at least before any implementation takes place. This appears frequently when coding to terminology (example: "Device-based Birth Control Method" in data dictionary vs. LOINC's "Birth Control Method"). Resolving these kinds of discrepancies early on is important.

**Comment by jamlung-ri** [comment]
What will the change control process be when it comes to updating the implementation guides? How will people know what changed and when between different versions?

**Comment by brynrhodes** [comment]
Regarding change control process, FHIR Implementation Guides have a _version_ which is used to stamp the version of all the resources published as part of that implementation guide. Whenever a version is _published_, it represents a snapshot of the contents of the IG at that point, and there is a _history_ page linked from all the versions that provides a directory of the versions with a change log for each. For example: http://hl7.org/fhir/us/cqfmeasures/history.html
This same approach can (and should) be used to version content implementation guides. So far we haven't actually _published_ any content IGs, we need a permanent host to do that.

**Comment by jamlung-ri** [comment]
There are a number of data modeling implications that currently exist in the data dictionary. We have often just used the implied data modeling (though sometimes we have changed the modeling in the DD), but it would be good to make the modeling across the DD consistent.

**Comment by jamlung-ri** [comment]
Validate that all SNOMED codes are from SNOMED International.
