### ISSUE TITLE
FHIR Mapping for Test Sensitivity

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#99]
For ID 1280 - Sensitivity of pregnancy test, this is an Observation about another Observation (i.e. 1275 - Information source for pregnancy status). How should we link these two IDs in a way that the tooling can understand them?

**Comment by brynrhodes** [comment]
The [focus](http://hl7.org/fhir/observation-definitions.html#Observation.focus) element of the Observation is how you would model that in the instance, but looking back through the Data Dictionary, I don't see the Data Element that represents the "Pregnancy Test" observation itself? Am I missing it? Is it 1987 (Perform pregnancy test), or is it part of 1269 (Pregnancy test recommended), as in, the data element is capturing the recommended sensitivity of the recommended test? Or is it capturing the sensitivity of the test that was performed? Or both?

**Comment by jennifershivers** [comment]
I think this is removed from the update DD, but I need to check if I am searching correctly.  @jamlung-ri @natschja

**Comment by jamlung-ri** [comment]
This was removed from the data dictionary.
